# Generated by Django 3.2.8 on 2021-11-02 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='user_list/placeholder.png', upload_to='user_list', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='osu_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
