# Generated by Django 3.2.8 on 2021-11-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='oauth_first_migrate',
            field=models.BooleanField(default=False),
        ),
    ]
