# Generated by Django 3.2.8 on 2021-11-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_actionlog_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='name',
            field=models.CharField(default='Beattosetto actions', max_length=5000),
        ),
    ]
