# Generated by Django 3.2.8 on 2021-11-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_actionlog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='log',
            field=models.FileField(blank=True, max_length=5000, null=True, upload_to='actions_logs'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='running_text',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
