# Generated by Django 3.2.8 on 2021-10-20 11:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('tags', models.TextField(blank=True, default=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beatmap_collections.collection')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatmap_collections.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=250)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatmap_collections.collection')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatmap_id', models.IntegerField(default=75)),
                ('beatmapset_id', models.IntegerField(default=1)),
                ('title', models.CharField(default='DISCO PRINCE', max_length=100)),
                ('artist', models.CharField(default='Kenji Ninuma', max_length=100)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('creator', models.CharField(default='peppy', max_length=100)),
                ('approved', models.CharField(default='1', max_length=10)),
                ('difficultyrating', models.FloatField(default='2.39774')),
                ('bpm', models.CharField(default='119.999', max_length=10)),
                ('version', models.CharField(blank=True, default='Normal', max_length=50)),
                ('url', models.URLField(default='https://osu.ppy.sh/beatmapsets/1#osu/75')),
                ('beatmap_card', models.ImageField(default='default_beatmap_cover.jpeg', upload_to='beatmap_card', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])])),
                ('beatmap_list', models.ImageField(default='default_beatmap_thumbnail.jpeg', upload_to='beatmap_list', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])])),
                ('description', models.TextField(blank=True, default=None)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('owner_approved', models.BooleanField(default=False)),
                ('count_normal', models.IntegerField(default=0)),
                ('count_slider', models.IntegerField(default=0)),
                ('count_spinner', models.IntegerField(default=0)),
                ('diff_approach', models.FloatField(default='0.0')),
                ('diff_drain', models.FloatField(default='0.0')),
                ('diff_overall', models.FloatField(default='0.0')),
                ('diff_size', models.FloatField(default='0.0')),
                ('max_combo', models.IntegerField(default=0)),
                ('playcount', models.IntegerField(default=0)),
                ('favourite_count', models.IntegerField(default=0)),
                ('total_length', models.IntegerField(default=0)),
                ('mode', models.IntegerField(default=0)),
                ('creator_id', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=100)),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beatmap_collections.collection')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
