# Generated by Django 3.2.8 on 2021-10-20 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beatmap_collections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmap',
            name='user',
            field=models.ForeignKey(default='peppywangInwZaa727', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='peppywangInwZaa727', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ratinglog',
            name='user',
            field=models.ForeignKey(default='peppywangInwZaa727', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
