# Generated by Django 3.2.8 on 2021-10-20 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beatmap_collections', '0002_auto_20211020_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatmap',
            name='collection',
        ),
        migrations.AddField(
            model_name='beatmap',
            name='collection',
            field=models.ManyToManyField(to='beatmap_collections.Collection'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='author',
            field=models.ForeignKey(default='peppywangInwZaa727', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
