# Generated by Django 3.2.8 on 2021-10-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0004_auto_20211020_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmap',
            name='collection',
            field=models.ManyToManyField(blank=True, to='beatmap_collections.Collection'),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatmap_collections.collection'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatmap_collections.collection'),
        ),
    ]
