# Generated by Django 3.2.8 on 2021-10-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0006_alter_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinglog',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatmap_collections.collection'),
        ),
    ]
