# Generated by Django 3.2.8 on 2021-10-21 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0008_auto_20211020_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='beatmap_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_list',
            field=models.ImageField(default='https://via.placeholder.com/600/240000', upload_to='collection_list', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
