# Generated by Django 3.2.7 on 2021-10-25 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0012_alter_collection_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_list',
            field=models.ImageField(default='collection_list/placeholder.jpg', upload_to='collection_list', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
