# Generated by Django 3.2.8 on 2021-10-25 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0016_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatmapEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('beatmap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beatmap_collections.beatmap')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beatmap_collections.collection')),
            ],
        ),
    ]
