# Generated by Django 3.2.8 on 2021-10-25 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beatmap_collections', '0017_beatmapentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beatmap',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='beatmap',
            name='description',
        ),
        migrations.RemoveField(
            model_name='beatmap',
            name='owner_approved',
        ),
        migrations.RemoveField(
            model_name='beatmap',
            name='user',
        ),
        migrations.AddField(
            model_name='beatmapentry',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beatmapentry',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beatmapentry',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='beatmapentry',
            name='owner_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beatmapentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
