# Generated by Django 3.2.7 on 2021-10-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0013_alter_collection_collection_list'),
        ('beatmap_collections', '0017_delete_profile'),
    ]

    operations = [
    ]
