# Generated by Django 3.2.8 on 2021-10-26 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0017_delete_profile'),
        ('beatmap_collections', '0018_auto_20211025_2204'),
    ]

    operations = [
    ]
