# Generated by Django 3.2.7 on 2021-10-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0018_merge_20211026_1619'),
        ('beatmap_collections', '0020_auto_20211026_1101'),
    ]

    operations = [
    ]
