# Generated by Django 3.2.8 on 2021-10-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0021_merge_20211026_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmap',
            name='tags',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
