# Generated by Django 3.2.8 on 2021-10-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0023_remove_beatmap_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmap',
            name='approved_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='last_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='submit_date',
            field=models.DateTimeField(),
        ),
    ]
