# Generated by Django 3.2.8 on 2021-10-27 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0024_auto_20211027_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmap',
            name='approved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='submit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
