# Generated by Django 3.2.8 on 2021-10-27 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0026_auto_20211027_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmapentry',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beatmap_collections.collection'),
        ),
    ]
