# Generated by Django 3.2.8 on 2021-10-27 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0027_alter_beatmapentry_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='beatmap_count',
        ),
    ]
