# Generated by Django 3.2.8 on 2021-10-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0028_remove_collection_beatmap_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='diff_aim',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='diff_speed',
            field=models.FloatField(default='0.0'),
        ),
    ]
