# Generated by Django 3.2.8 on 2021-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0029_auto_20211028_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='genre_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='language_id',
            field=models.IntegerField(default=0),
        ),
    ]
