# Generated by Django 3.2.8 on 2021-11-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0030_auto_20211028_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beatmap_collections.collection'),
        ),
    ]
