# Generated by Django 3.2.7 on 2021-11-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0032_auto_20211104_0923'),
        ('beatmap_collections', '0032_auto_20211104_1628'),
    ]

    operations = [
    ]
