# Generated by Django 3.2.9 on 2021-11-12 20:44

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('beatmap_collections', '0034_auto_20211108_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allow_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='background_align',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', max_length=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
