# Generated by Django 3.2.9 on 2021-11-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0035_auto_20211112_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratinglog',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='ratinglog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='RatingLog',
        ),
    ]
