# Generated by Django 3.2.9 on 2021-11-20 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0041_auto_20211120_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmap',
            name='beatmap_card',
            field=models.ImageField(blank=True, default='default_beatmap_cover.png', null=True, upload_to='beatmap_card', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='beatmap',
            name='beatmap_list',
            field=models.ImageField(blank=True, default='default_beatmap_thumbnail.png', null=True, upload_to='beatmap_list', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
