# Generated by Django 3.2.9 on 2021-11-24 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0042_auto_20211120_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='beatmap_cover',
            field=models.ImageField(blank=True, default='default_beatmap_cover.png', null=True, upload_to='beatmap_cover', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'gif', 'jpg', 'jpeg', 'bmp', 'svg', 'webp'])]),
        ),
    ]
