# Generated by Django 3.2.9 on 2021-11-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatmap_collections', '0043_beatmap_beatmap_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beatmapentry',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
